Twitt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TwitterClone/', include('TwitterClone.urls')),
]

TwitterClone/urls.py
from django.urls import path
from . import views


app_name = "Twitter"
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.Qlogin.as_view(), name='index'),
    path('path/', views.PostLogin.as_view(), name='login-quickly'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign-up/', views.SignupView.as_view(), name='sign-up'),
    path('home/', views.PostView.as_view(), name='home')
    ]

TwitterClone/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
import datetime
# Create your models here.


class Account(AbstractUser):
    # Username = models.CharField(max_length=20)
    # Password = models.CharField(max_length=50)
    # cre_date = models.DateTimeField('date published', default=timezone.now())
    age = models.IntegerField(default=0)
    sex_choice = ((0, 'Nữ'), (1, 'Nam'))
    address = models.CharField(default='', max_length=50)
    sex = models.IntegerField(choices=sex_choice, default='1')
    phone = models.CharField(max_length=11)


class Post(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    context = models.CharField(max_length=1000)
    time_creat = models.DateTimeField()

    def __str__(self):
        return str(self.context)


class Comment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    cmt = models.CharField(max_length=500)

    def __str__(self):
        return str(self.user)


class Like(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return str(self.likes)

TwitterClone/forms.py
from django import forms
from .models import Account, Post, Comment, Like



class QuickLogin(forms.ModelForm):
    class Meta:
        model = Account
        fields = {'username', 'password', }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username', 'placeholder': 'Tên đăng nhập...'}),
            'password': forms.TextInput(attrs={'class': 'password', 'placeholder': 'Mật khẩu...', 'type': 'password'})
        }


class Signup(forms.ModelForm):
    class Meta:
        model = Account

        fields = {'username', 'password', 'sex', 'email', 'phone', }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username', 'placeholder': 'Tên đăng nhập...'}),
            'password': forms.TextInput(attrs={'class': 'password', 'placeholder': 'Mật khẩu...', 'type': 'password'}),
            'email': forms.TextInput(attrs={'class': 'email', 'placeholder': 'Email'}),
            'phone': forms.TextInput(attrs={'class': 'phone', 'placeholder': 'Số điện thoại...'}),
            'sex': forms.Select(attrs={'class': 'sex'})
        }


class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = {'user', 'context', }
        widgets ={

            'context': forms.TextInput(attrs={'class': 'contexted', 'placeholder': 'Chuyện gì đang xảy ra ?'})

        }

TwitterClone/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login
from .forms import QuickLogin, Signup, CreatePost

from . models import Account

from  django.contrib.auth.models import User
# Create your views here.


# class IndexView(View):
#     def get(self, request):
#         return render(request, 'TwitterClone/index.html')


class Qlogin(View):
    def get(self, request):
        lg = QuickLogin()
        return render(request, 'TwitterClone/index.html', {'up': lg})


class PostLogin(View):
    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        user_login = authenticate(username=username, password=password)
        print(user_login)
        if user_login is None:
            lg = QuickLogin()
            context = {'up': lg}
            return render(request, 'TwitterClone/index.html', context)
        login(request, user_login)
        tg = username
        pt = CreatePost()
        return render(request, 'TwitterClone/home.html', {'acc': tg, 'post':pt})


class LoginView(View):
    def get(self, request):
        lg = QuickLogin()
        return render(request, 'TwitterClone/Login.html', {'up': lg})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_login = authenticate(username=username, password=password)
        print(user_login)
        if user_login is None:
            lg = QuickLogin()
            context = {'up': lg}
            return render(request, 'TwitterClone/Login.html', context)
        login(request, user_login)
        tg = username
        pt = CreatePost()
        return render(request, 'TwitterClone/home.html', {'acc': tg, 'post': pt})


class SignupView(View):
    def get(self, request):
        si = Signup()
        return render(request, 'TwitterClone/Sign-up.html', {'in': si})

    def post(self, request):
        si = Signup(request.POST)
        if si.is_valid():

            user = Account()
            user.username = si.cleaned_data.get('username')
            user.set_password(si.cleaned_data.get('password'))
            user.email = si.cleaned_data.get('email')
            user.phone = si.cleaned_data.get('phone')
            user.sex = si.cleaned_data.get('sex')
            # user.is_staff = False
            # user.is_superuser = True
            user.save()
            user.refresh_from_db()
            lg = QuickLogin()
            return render(request, 'TwitterClone/Login.html', {'up': lg})

        else:
            # return render(request, 'TwitterClone/Sign-up.html', {'in': si})
            return HttpResponse('false')


class PostView(View):
    def get(self, request):

        return render(request, 'TwitterClone/home.html', {'post': pt})

TwitterClone/templates/TwitterClone/Login.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/icontwitt.png' %}">
    <title>Đăng nhập vào Twitter</title>

     <link rel="stylesheet" type="text/css" href="{% static 'TwitterClone/stylelogin.css'%}">
</head>
<body>
    <div class="contain">
        <div class="space">
        <div class="menu-banner">
            <div class="menu">
                <div class="left-context">
                    <ul>
                        <li><img src="{% static 'images/twitt-icon.jpg'%}" width="23px" height="23px" align="center">&nbsp;<a href="{% url 'Twitter:index'%}">Trang chủ</a></li>
                        <li style="width: 68px !important;"><a href="#">Giới thiệu</a></li>
                    </ul>
                </div>
                <div class="right-language">
                    <span>Ngôn ngữ : </span>&nbsp;<a href="#">Tiếng Việt</a>
                </div>
            </div>
        </div>
            </div>
        <div class="form">
        <div class="form-login">
                <div class="ft-login">
            <form action="{% url 'Twitter:login'%}" method="post">
                {%  csrf_token %}
                <h2><b>Đăng nhập vào Twitter</b></h2>
                <div class="login-username">{{ up.username }}</div>
                <div class="login-password">{{ up.password }}</div>
                <div class="btn-login"><input type="submit" value="Đăng nhập"><a href="#">Quên mật khẩu ?</a></div>
            </form>
                </div>
        </div>
            <div class="context-tw">
                <div class="context-in">
                    <p>Mới dùng Twitter? &nbsp;<a href="#">Đăng kí ngay >></a></p>
                    <p>Bạn đã dùng Twitter qua tin nhắn văn bản &nbsp;<a href="#">Kích hoạt tài khoản của bạn? >></a></p>
                </div>
            </div>
            </div>
    </div>
</body>
</html>

TwitterClone/templates/TwitterClone/Sign-up.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/icontwitt.png' %}">
    <title>Đăng kí tài khoản Twitter</title>

     <link rel="stylesheet" type="text/css" href="{% static 'TwitterClone/stylesignup.css'%}">
</head>
<body>
    <div class="contain">
        <div class="space">
        <div class="menu-banner">
            <div class="menu">
                <div class="left-context">
                    <ul>
                        <li><img src="{% static 'images/twitt-icon.jpg'%}" width="23px" height="23px" align="center">&nbsp;<a href="{% url 'Twitter:index'%}">Trang chủ</a></li>
                        <li style="width: 68px !important;"><a href="#">Giới thiệu</a></li>
                    </ul>
                </div>
                <div class="right-language">
                    <span>Ngôn ngữ : </span>&nbsp;<a href="#">Tiếng Việt</a>
                </div>
            </div>
        </div>
            </div>
        <div class="form">
        <div class="form-sign-up">
                <div class="ft-sign-up">
            <form action="{% url 'Twitter:sign-up'%}" method="post">
                {%  csrf_token %}
                <h2><b>Tạo tài khoản của bạn</b></h2>
                <div class="sign-up-username">{{ in.username }}</div>
                <div class="sign-up-password">{{ in.password }}</div>
                <div class="sign-up-email">{{ in.email }}</div>
                <div class="sign-up-sex">{{in.sex}}</div>
                <div class="sign-up-phone">{{in.phone}}</div>
                <div class="btn-sign-up"><input type="submit" value="Đăng kí"></div>
            </form>
                </div>
        </div>
            <div class="context-tw">
                <div class="context-in">
                    <p>Trải nghiệm tuyệt vời cùng Twitter</p>
                    <p>Bạn đã dùng Twitter qua tin nhắn văn bản &nbsp;<a href="#">Kích hoạt tài khoản của bạn? >></a></p>
                </div>
            </div>
            </div>
    </div>
</body>
</html>

TwitterClone/templates/TwitterClone/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/icontwitt.png' %}">
    <title>Đăng kí tài khoản Twitter</title>

     <link rel="stylesheet" type="text/css" href="{% static 'TwitterClone/stylehome.css'%}">
</head>
<body>
    <div class="contain">
        <div class="space">
        <div class="menu-banner">
            <div class="menu">
                <div class="left-context">
                    <ul>
                        <li><img src="{% static 'images/twitt-icon.jpg'%}" width="23px" height="23px" align="center">&nbsp;<a href="{% url 'Twitter:home'%}">Trang chủ</a></li>
                        <li style="width: 68px !important;"><a href="#">Thông báo</a></li>
                    </ul>
                </div>
                <div class="right-language">
                   <input type="text" placeholder="Tìm kiếm">

                </div>
                <div class="acc">
                    <img src="{% static 'images/user.png'%}">
                    <div class="name">{{acc}}</div>
                    <div class="logout"><a href="{% url 'Twitter:login'%}"><img src="{% static 'images/logout.png'%}"></a></div>
                </div>
            </div>
        </div>
            </div>
        <div class="form">
                <div class="create-post">
                    <div class="pt-context">{{ post.context }}</div>
                </div>
                <div class="show">B</div>
            </div>
    </div>
</body>
</html>

TwitterClone/templates/TwitterClone/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/icontwitt.png' %}">
    <title>Twitter.Đó là điều đang diễn ra</title>
    <link rel="stylesheet" type="text/css" href="{% static 'TwitterClone/styleindex.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
<div class="contain">
    <div class="main">
        <div class="left-background">

            <div class="intro">
                <div class="follow-hobie">
                    <i class="fas fa-search" style="padding-right: 15px;"></i>Theo dõi những sở thích của bạn

                </div>
                <div class="listen-ever">
                    <i class="far fa-user" style="padding-right: 15px;"></i>Nghe nội dung mọi người đang bàn luận

                </div>
                <div class="join">
                    <i class="far fa-comment" style="padding-right: 15px;"></i>Tham gia vào cuộc trò chuyện

                </div>
            </div>
        </div>
        <!--Xử lí form-->


        <div class="right-context">
        <div class="quick-login">
            <form method="post" action="{% url 'Twitter:login-quickly' %}">
                {% csrf_token %}
                <!--<div class="login-username"><input type="text" placeholder="Tên người dùng..."></div>-->
                <!--<div class="login-password"><input type="password" placeholder="Mật khẩu..."></div>-->
                <div class="login-username">{{ up.username }}</div>
                <div class="login-password">{{ up.password }}</div>
                <div class="btn"><button type="submit" class="btn btn-outline-primary">Đăng nhập</button></div>
                <div class="forget-password"><a href="#" >Quên mật khẩu ?</a></div>
            </form>
        </div>
            <div class="get-in-page">
                <div class="icon-twitter"><img src="{% static 'images/twitt-icon.jpg'%}"></div>
                <p style="font-family:Arial; padding-bottom: 20px;font-size:28px; ">Xem những sự kiện đang xảy ra trên thế giới ngay lúc này</p>
                <div class="homepage-signinup">
                    <p style="font-size: 20px; font-weight: bold">Tham gia Twitter ngay hôm nay :</p>
                    <div class="btn-register"><a href="{% url 'Twitter:sign-up' %}"><input type="submit" value=" Đăng kí"/></a></div>
                    <div class="btn-sign-in"><a href="{% url 'Twitter:login' %}"><input type="submit" value="Đăng nhập"/></a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="list-menu">
        <ul>
            <li><a href="#">Giới thiệu</a></li>
            <li><a href="#">Trung tâm trợ giúp</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Trạng thái</a></li>
            <li><a href="#">Việc làm</a></li>
            <li><a href="#">Chính sách</a></li>
            <li><a href="#">Cookie</a></li>
            <li><a href="#">Quảng cáo</a></li>
            <li><a href="#">Thương hiệu</a></li>
            <li><a href="#">Ứng dụng</a></li>
            <li><a href="#">Danh mục</a></li>
            <li><a href="#">Cài đặt</a></li>

        </ul>
    </div>
</div>
</body>
</html>